version: "3.8"
services:
  db:
    image: postgres:15
    container_name: daolearn-db
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: plataforma
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
